[package]
name = "aten"
version = "0.1.0"
edition = "2021"

license = "Apache-2.0"
repository = "https://github.com/pacujo/aten"

[dependencies]
lazy_static = "1.4"
libc = "0.2"
r3 = { git = "https://github.com/pacujo/r3" }
